# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vnVDU21IvM8_FxnLH62iOaLm8kKoYqm6
"""

import streamlit as st
import pandas as pd
from pycaret.classification import load_model, predict_model

st.set_page_config(page_title="Credit Scoring com PyCaret", layout="wide")
st.title("🏦 Credit Scoring App (via PyCaret)")

# 📁 Upload do arquivo CSV
uploaded_file = st.file_uploader("Faça upload do arquivo CSV para escoragem", type=["csv"])

# 📦 Carregar modelo salvo pelo PyCaret
@st.cache_resource
def carregar_modelo():
    return load_model("modelo_lightgbm_pycaret")

modelo = carregar_modelo()

# ✅ Quando o arquivo for enviado
if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)

    st.subheader("📄 Dados carregados:")
    st.dataframe(df.head())

    # 🔮 Previsões
    resultado = predict_model(modelo, data=df)

    st.subheader("📊 Resultado da escoragem:")
    st.dataframe(resultado.head())

    # 💾 Botão de download
    csv = resultado.to_csv(index=False).encode("utf-8")
    st.download_button(
        label="⬇️ Baixar resultado como CSV",
        data=csv,
        file_name="resultado_escoragem.csv",
        mime="text/csv"
    )
